### ISSUE TITLE
RawToolsGUI-beta fails when using X!Tandem

### ISSUE THREAD

**Issue by roberthardt** [kevinkovalchik/RawTools#36]
**Describe the bug**
I tried to run two raw files trough the tool with a X!Tandem search enabled. Without it everything runs trough smoothely.

**Description of raw file**
relatively small and simply run. BSA 60 min gradient DDA.

**Command line arguments**
I used the GUI

**Command line output**
Please paste the entire output from the command line, if applicable (i.e. everything that appeared after you hit enter until things stopped working).
```
2 file(s) to process

Processing: C:\Users\50112675\Documents\Test_rawtools\190506_BSA_10.raw

Determing MS analysis order... Done!
Extracting scan indices: 100%
Checking for orphaned scans: 100%

================ Scan indexing report ================
Total scans in file: 9089
Scans linked: 9089

Orphan scans:
None!

All scans accounted for!
======================================================

Extracting reaction events: 100%
Extracting scan data: 100%
Extracting trailer extras: 100%
Extracting precursor masses: 100%
Extracting retention times: 100%
Analyzing precursor peaks: 100%
Refining precursor charge and monoisotopic mass: 100%
Calculating meta data
  MS1 isolation interference
  MS2 scan cycle density
  Ion injection time
  Duty cycle
  Intensity distribution
  Summed intensities
Calculating metrics


Writing MGF file: 100%
Writing Ms TIC chromatogram: 0%
Writing Ms TIC chromatogram: 100%
Writing Ms base peak chromatogram: 0%
Writing Ms base peak chromatogram: 100%
Writing Ms TIC chromatogram: 0%
Writing Ms TIC chromatogram: 100%
Writing Ms base peak chromatogram: 0%
Writing Ms base peak chromatogram: 100%

Writing MGF file: 100%
Reading FASTA file
Writing target-decoy database: 100%

X! TANDEM Alanine (2017.2.1.4)

Loading spectra| (mgf).. loaded.
Spectra matching criteria = 3868
Starting threads .|.|. started.
Computing models:
        t
        waiting for 2|3| done.

        sequences modelled = 0 ks
Model refinement:

        waiting for 2|3| done.

Merging results:
        from 2.3.

Creating report:
        initial calculations  ..... done.
        sorting  ..... done.
        finding repeats ..... done.
        evaluating results ..... done.
        calculating expectations ..... done.
        writing results ..... done.

Valid models = 399



Unbehandelte Ausnahme: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RawTools.Utilities.AdditionalMath.Percentile(Double[] Values, Int32 percentile) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\Utilities\Utilities.cs:line 322
   at RawTools.QC.SearchQC.ParsePSMs(SearchMetricsContainer searchMetrics, PsmDataCollection psmCollection, WorkflowParameters parameters) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\QC\SearchQC.cs:line 239
   at RawTools.QC.SearchQC.ParseSearchResults(SearchMetricsContainer searchMetrics, WorkflowParameters parameters, String rawFileName) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\QC\SearchQC.cs:line 73
   at RawTools.WorkFlows.WorkFlowsDDA.UniversalDDA(IRawFileThreadManager rawFileThreadManager, WorkflowParameters parameters, QcDataCollection qcDataCollection) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\WorkFlows\DDA.cs:line 155
   at RawTools.Program.DoStuff(UniversalOptions opts) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\Program.cs:line 656
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at RawTools.Program.Main(String[] args) in C:\Users\Kevin\Documents\GSC\Projects\RawTools\RawTools\Program.cs:line 69

```

**Screenshots**

**Desktop & RawTools information:**
 - OS: Win 10
- RawTools version: 1.0.0

**Additional context**

**Comment by roberthardt** [comment]
I fixed it. My input database was simply to small.

Regards
Robert
