### ISSUE TITLE
System.UnauthorizedAccessException (((

### ISSUE THREAD

**Issue by KanshinED1** [kevinkovalchik/RawTools#55]
**Describe the bug**
I've been using RAW tools for a long time and getting this error for the first time. Haven't changed any permission of file locations and 2-3 weels ago everything was working...
Now it says "System.UnauthorizedAccessException"

**Description of raw file**
Just a standard DDA HeLa run (MS2 HCD)

**Command line arguments**
RawTools.exe -d A:\TempDataStorage\RawTools_QC\1_PlaceRawFilesHere -pu

**Command line output**
Please paste the entire output from the command line, if applicable (i.e. everything that appeared after you hit enter until things stopped working).
```
2020-09-30 13:07:29.817 -04:00 [INF] Program started with arguments: -d A:\TempDataStorage\RawTools_QC\1_PlaceRawFilesHere -pu
2020-09-30 13:07:29.972 -04:00 [INF] Files to be processed, provided as directory: A:\TempDataStorage\RawTools_QC\1_PlaceRawFilesHere\200929_H_ValkLC_WR_HeLa_80min.raw
2020-09-30 13:07:30.017 -04:00 [ERR] 200929_H_ValkLC_WR_HeLa_80min.raw reports error code: -2147024891. The associated message is: 
Exception type: System.UnauthorizedAccessException
Message       : Access to the path is denied.
Stacktrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at ThermoFisher.CommonCore.RawFileReader.Readers.MemoryMappedRawFile.GetRandomAccessViewer(Int64 offset, Int64 size, MemoryMappedFileAccess fileAccess)
   at ThermoFisher.CommonCore.RawFileReader.Readers.MemoryMappedRawFileManager.GetRandomAccessViewer(Guid loaderId, String mapName, Int64 offset, Int64 size, Boolean inAcquisition, MemoryMappedFileAccessMode accessMode, MemoryMappedFileType type)
   at ThermoFisher.CommonCore.RawFileReader.StructWrappers.VirtualDevices.DeviceBase.NonAcquisitionInitializer(VirtualControllerInfo deviceInfo, String rawFileName, Int32 fileRevision)
   at ThermoFisher.CommonCore.RawFileReader.StructWrappers.VirtualDevices.MassSpecDevice..ctor(Guid loaderId, VirtualControllerInfo deviceInfo, String rawFileName, Int32 fileRevision, Boolean isInAcquisition, Boolean oldRev)
   at ThermoFisher.CommonCore.RawFileReader.StructWrappers.VirtualDevices.DeviceFactory.GetDevice(Guid loaderId, VirtualControllerInfo deviceInfo, String rawFileName, Int32 fileVersion, Boolean isInAcquisition)
   at ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader.<>c__DisplayClass62_0.<InitialDeviceLists>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoaderHelper.GetVirtualControllerInfo(RawFileLoader loader, Device instrumentType, Int32 instrumentIndex, IReadOnlyList`1 virtualControllerInfos, Lazy`1[] detectors, IDevice& selectedDevice)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/48643843/94718318-998dab00-031f-11eb-9a17-6a3d5096b414.png)

**Desktop & RawTools information:**
 - OS: Microsoft Windows 10
- RawTools version: 2.0.2

**Additional context**

**Comment by KanshinED1** [comment]
My bad, just realized that it was a corrupted raw file(((
